#!/usr/bin/env julia
# Convert the Shaw et al. (2025) per-glacier decoupling table from its published
# MATLAB v7.3 (= HDF5) form into a compact CSV vendored in this directory.
#
# Run manually when the upstream dataset is updated; the package itself never reads
# the .mat file, so HDF5.jl stays out of Project.toml.
#
#   julia --project=/some/scratch/env data/make_shaw2025_decoupling.jl [path/to/HISTORICAL_DECOUPLING_ESTIMATES_DATABASE.mat]
#
# Source: Shaw et al. (2025), Nature Climate Change. Dataset:
#   https://doi.org/10.5281/zenodo.14044846
#   -> HISTORICAL_DECOUPLING_ESTIMATES_DATABASE.mat
#
# See docs/on_glacier_temperature_correction.md for why the published lookup table is
# used rather than the paper's five-predictor regression (Table S2 has sign errors in
# a4/a5 and is not reproducible from the paper).

using HDF5, Printf, CodecZlib

const DEFAULT_SRC = joinpath(@__DIR__, "..", "docs", "references", "shaw2025_decoupling",
                             "HISTORICAL_DECOUPLING_ESTIMATES_DATABASE.mat")
const DEST = joinpath(@__DIR__, "shaw2025_glacier_decoupling.csv.gz")

src = length(ARGS) >= 1 ? ARGS[1] : DEFAULT_SRC
isfile(src) || error("source .mat not found: $src\nDownload from https://doi.org/10.5281/zenodo.14044846")

@info "reading" src
rgi_id, region, lat, lon, ele, k, k_lower = h5open(src) do f
    g = f["HISTORICAL_K"]
    # RGI_ID is an array of HDF5 object references, each pointing at a char array
    # holding a string like "RGI60-01.00001".
    refs = read(g["RGI_ID"])
    ids = [String(Char.(vec(read(f[r])))) for r in refs]
    rd(n) = vec(read(g[n]))
    ids, rd("REGION"), rd("LAT"), rd("LON"), rd("ELE"), rd("K"), rd("K_CI")
end

n = length(rgi_id)
@info "glaciers" n
n == 186_792 || @warn "unexpected row count (expected 186792 for the v1 dataset)" n

# ELE carries a -999 fill for a handful of glaciers; keep the row (K is still valid)
# but write the fill as an empty field so it parses as `missing` rather than a real
# elevation of -999 m.
nfill = count(<(-900), ele)
nfill > 0 && @info "ELE fill values written as empty" nfill

open(GzipCompressorStream, DEST, "w") do io
    println(io, "# Shaw et al. (2025) Nature Climate Change - per-glacier air temperature")
    println(io, "# decoupling factor k for RGI v6 glaciers. Generated by")
    println(io, "# data/make_shaw2025_decoupling.jl from HISTORICAL_DECOUPLING_ESTIMATES_DATABASE.mat")
    println(io, "# (https://doi.org/10.5281/zenodo.14044846). See")
    println(io, "# docs/on_glacier_temperature_correction.md for usage and caveats.")
    println(io, "#")
    println(io, "# rgi_id  : Randolph Glacier Inventory v6 identifier")
    println(io, "# region  : RGI first-order region number (05 Greenland and 19 Antarctic are ABSENT)")
    println(io, "# lat,lon : glacier mean centroid, decimal degrees (lon -180..180)")
    println(io, "# ele     : glacier mean elevation, m a.s.l. (empty where unavailable)")
    println(io, "# k       : decoupling factor, unitless, clamped to [0.2, 1.0] upstream")
    println(io, "# k_lower : lower bound of the 95% CI on k, unitless. This is the upstream")
    println(io, "#           K_CI column, which is an absolute bound and NOT a half-width:")
    println(io, "#           it sits below k by ~0.028 on average and is left unclamped, so it")
    println(io, "#           can be negative. Upper bound is not published.")
    println(io, "rgi_id,region,lat,lon,ele,k,k_lower")
    for i in 1:n
        elestr = ele[i] < -900 ? "" : @sprintf("%.0f", ele[i])
        # 4 decimals on k/k_ci is well below the dataset's own uncertainty (RMSE 0.105)
        # and 5 on lat/lon is ~1 m; this keeps the file an order of magnitude smaller
        # than the .mat without losing anything meaningful.
        println(io, rgi_id[i], ',', Int(region[i]), ',',
                @sprintf("%.5f", lat[i]), ',', @sprintf("%.5f", lon[i]), ',',
                elestr, ',', @sprintf("%.4f", k[i]), ',', @sprintf("%.4f", k_lower[i]))
    end
end

@info "wrote" DEST size_mb=round(filesize(DEST) / 1024^2, digits=2)
